### ISSUE TITLE
Make HTTPS optional for fetching

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/django-prices-vatlayer#6]
Hi!

A little issue when fetching the tax rates with `DEBUG = False`, if fetches tax rates but the user may not have a paid vat-layer account.

```
django.core.exceptions.ImproperlyConfigured: Access Restricted - Your current Subscription Plan does not support HTTPS Encryption.
```

cf. https://github.com/mirumee/django-prices-vatlayer/blob/245fd7571471c26cdf5f8aa0c8a5300a5c097915/django_prices_vatlayer/utils.py#L16-L17

### Proposed solution
We could add a new settings key `VATLAYER_USE_HTTPS` set to `False` by default as the paid user may be looking to ensure HTTPS.

**Comment by NyanKiyoshi** [comment]
Any feedback?

**Comment by maarcingebala** [comment]
I agree we should add such setting since HTTPS is available only in paid plans.
